all:
  vars:
    ansible_user: root
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    k3s_master_HOME:
      ansible_host: 152.152.152.90
      ansible_ssh_private_key_file: ~/.ssh/server_root
